x = Artist.create!(name: 'Adams')
y = Artist.create!(name: 'John')
z = Artist.create!(name: 'Foo Fighters')

Song.create!(title: 'Song 1', artist_id: x.id)
Song.create!(title: 'Song 2', artist_id: y.id)
Song.create!(title: 'Song 3', artist_id: y.id)
Song.create!(title: 'Song 4', artist_id: z.id)
Song.create!(title: 'Song 34', artist_id: z.id)
Song.create!(title: 'Song 35', artist_id: z.id)
